=head1 NAME

Term::Sk1 - These are sidenotes for the Module Term::Sk.

=head1 SIDENOTES

(This is just a stub - Sidenotes are not yet implemented)

=head2 Standard Items

=over

=item This is item 1

=item This is item 2

=back

=head2 Other Items

=over

=item This is item 3

=item This is item 4

=back

=head1 AUTHOR

Klaus Eichner, January 2008

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2008 by Klaus Eichner

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
