---
abstract: 'Perl extension for displaying a progress indicator on a terminal'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.3
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-Sk
provides:
  Term::Sk:
    file: lib/Term/Sk.pm
    version: 0.14
resources:
  license: http://dev.perl.org/licenses/
version: 0.14
