---
name: Term-Sk
version: 0.03
author:
abstract: Perl extension for displaying a progress indicator on a terminal
license: perl
configure_requires:
  Module::Build: 0.340201
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  Term::Sk:
    file: lib/Term/Sk.pm
    version: 0.03
resources:
  license: http://dev.perl.org/licenses/
